export const categoryNames = {
	"ArtsMusic": "Arts Music",
	"Biographies": "Biographies",
	"Comics": "Comics",
	"ComputersvsTech": "Computers",
	"Cooking": "Cooking",
	"EduReference": "Education Reference",
	"Entertainment": "Entertainment",
	"GayLesbian": "GayLesbian",
	"Health": "Health",
	"Horror": "Horror",
	"Kids": "Kids",
	"LiteratureFiction": "Literature Fiction",
	"Mysteries": "Mysteries",
	"Religion": "Religion",
	"Romance": "Romance",
	"Sci-FiFantasy": "Sci-Fi Fantasy",
	"ScienceMath": "Science Math",
	"Sports": "Sports",
	"Teenfic": "Teenfic",
	"TrueCrime": "True Crime",
	"Others": "Others",
}